### ISSUE TITLE
How to run the plugin when the scroll is 0

### ISSUE THREAD

**Issue by compojoom** [jaseowns/onImpression#1]
The plugin works great when I start scrolling, or if the default position of the scroll is not 0px. 
But when I load the page for the first time my div scroll has 0px and the elemenets taht I'm tracking are already visible. Until I manually scroll my callback isn't fired? Is there a way to execute the plugin with scroll 0 or am I missing something?

**Comment by compojoom** [comment]
Most probably the problem was the fact that the elements that I'm looking for are not in the dom. There are part of a collection that is rendered... Once the collection was rendered I've triggered a resize event on my scrollable area and now everything seems fine.

**Comment by jaseowns** [comment]
Hey cool, I just about to tell you -- I wrap my .onImpression trigger under a slight delay (using setTimeout) to help grab any initial elements.  Glad you found a solution!

**Comment by compojoom** [comment]
Interesting. Actually my resize event in the collection onRender didn't have any effect untill I used the setTimeout myself. Now you tell me that you are using this as well. 
That's strange. Actually at the moment when I init onImpression the element should be in the browser dom. So it's really strange that it doesn't have any effect. In my opinion something else is going on, like a racing condition or whatever... And setTimeout is just a workaround... I'm using it with 0ms... http://stackoverflow.com/questions/779379/why-is-settimeoutfn-0-sometimes-useful
